project_id = "msydzhzolwourcdmqxvn"

[functions.send-application-notification]
verify_jwt = false

[functions.submit-application]
verify_jwt = false

[functions.update-application-referral]
verify_jwt = false

[functions.send-weekly-analytics]
verify_jwt = false
