import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  { ignores: ["dist"] },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  // ── Scoped overrides for surfaces where `any` is intrinsic ─────────────
  // These are NOT a broad escape hatch. They're for code paths that
  // legitimately receive unknown-shape data from external systems.
  {
    files: ["src/integrations/supabase/types.ts"],
    rules: {
      // Auto-generated by `supabase gen types typescript`. Regenerates wipe
      // any hand-typed fixes. Lint can't help here.
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-empty-object-type": "off",
    },
  },
  {
    files: ["supabase/functions/**/*.ts"],
    rules: {
      // Deno edge functions receive webhook payloads from Stripe, ReadyMode,
      // Instagram, Resend, etc — the shape is by definition `unknown` until
      // we validate it. Requiring extra casting at every property access
      // doesn't add safety; zod validation is the real guarantee where it
      // matters (submit-application, update-application-referral, etc).
      "@typescript-eslint/no-explicit-any": "off",
    },
  },
  {
    files: ["scripts/**/*", "tasks/**/*"],
    rules: {
      // Ops scripts — pragmatic typing, not load-bearing.
      "@typescript-eslint/no-explicit-any": "off",
    },
  },
);
