/**
 * sync.ts — bridge tasks.json <-> Apple Reminders <-> Supabase.
 *
 * Limitations (called out per spec):
 *   - Apple Reminders has no public REST API. We use AppleScript via osascript.
 *     AppleScript exposes: name, body, due date, completed, id, list. It does NOT
 *     expose tags, custom status, priority round-trip, or arbitrary metadata.
 *     For everything beyond the basics we keep the data only in tasks.json /
 *     Supabase, using `reminderExternalId` to bridge.
 *   - On non-macOS hosts the Reminders sync is a no-op (logged + exit 0).
 *   - Match strategy when reminderExternalId is missing:
 *         fingerprint = list + dueDate(YYYY-MM-DD) + lowercased title
 */
import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import {
  Task,
  TaskList,
  ALL_LISTS,
  fingerprint,
  PRIORITY_RANK,
} from "./schema.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const TASKS_PATH = join(__dirname, "tasks.json");
const TODAY_PATH = join(__dirname, "today.md");

// ─── Local file ─────────────────────────────────────────────────────────
export function loadStore(): { version: number; updatedAt: string; tasks: Task[] } {
  if (!existsSync(TASKS_PATH)) {
    return { version: 1, updatedAt: new Date().toISOString(), tasks: [] };
  }
  return JSON.parse(readFileSync(TASKS_PATH, "utf8"));
}
export function saveStore(store: { tasks: Task[] }) {
  const out = {
    version: 1,
    updatedAt: new Date().toISOString(),
    tasks: store.tasks,
  };
  writeFileSync(TASKS_PATH, JSON.stringify(out, null, 2) + "\n");
}

// ─── Today markdown ─────────────────────────────────────────────────────
export function rebuildTodayMd(tasks: Task[]) {
  const today = new Date().toISOString().slice(0, 10);
  const isToday = (t: Task) =>
    t.due && t.due.slice(0, 10) <= today && t.status !== "done" && t.status !== "cancelled";
  const open = tasks
    .filter((t) => t.status === "open" || t.status === "in_progress")
    .sort((a, b) => {
      const p = PRIORITY_RANK[b.priority] - PRIORITY_RANK[a.priority];
      if (p !== 0) return p;
      return (a.due || "9999-12-31").localeCompare(b.due || "9999-12-31");
    });

  const today_items = open.filter(isToday);
  const upcoming = open.filter((t) => !isToday(t));

  const renderRow = (t: Task) => {
    const due = t.due ? ` · *${t.due.slice(0, 10)}*` : "";
    const tags = t.tags.length ? ` ${t.tags.map((tag) => `\`#${tag}\``).join(" ")}` : "";
    return `- [ ] **[${t.priority}]** ${t.title}${due}${tags} _(list: ${t.list}, src: ${t.source})_`;
  };

  let md = `# Today — ${today}\n\nAuto-generated by \`tasks/sync.ts\`. Edit through the CLI or React UI, not by hand.\n\n`;
  md += `## Today / overdue\n\n`;
  md += today_items.length
    ? today_items.map(renderRow).join("\n") + "\n"
    : "_(none — clear day)_\n";
  md += `\n## Upcoming (open)\n\n`;
  md += upcoming.length
    ? upcoming.map(renderRow).join("\n") + "\n"
    : "_(none open)_\n";
  writeFileSync(TODAY_PATH, md);
}

// ─── Apple Reminders bridge ─────────────────────────────────────────────
const IS_MAC = process.platform === "darwin";

function osa(script: string): string {
  if (!IS_MAC) return "";
  const r = spawnSync("/usr/bin/osascript", ["-e", script], {
    encoding: "utf8",
    timeout: 30000,
  });
  if (r.status !== 0) {
    throw new Error(`osascript failed (${r.status}): ${r.stderr || r.stdout}`);
  }
  return (r.stdout || "").trim();
}

function ensureListExists(list: TaskList) {
  if (!IS_MAC) return;
  const script = `
    tell application "Reminders"
      if not (exists list "${list}") then
        make new list with properties {name:"${list}"}
      end if
    end tell
  `;
  osa(script);
}

function escAS(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

/** Push a single task to Reminders. Returns reminder id. */
export function pushToReminders(t: Task): string | null {
  if (!IS_MAC) return null;
  ensureListExists(t.list);
  const dueClause = t.due
    ? ` ,remind me date:(my parseISO("${t.due}"))`
    : "";
  // We rely on AppleScript date arithmetic via a helper subroutine.
  const script = `
    on parseISO(s)
      set ms to date "1/1/1970"
      set epochSecs to (do shell script "date -j -f '%Y-%m-%dT%H:%M:%S' '" & s & "T00:00:00' '+%s' 2>/dev/null || date -j -f '%Y-%m-%d' '" & s & "' '+%s'")
      return ms + (epochSecs as integer)
    end parseISO
    tell application "Reminders"
      set L to list "${t.list}"
      set newR to make new reminder at end of L with properties {name:"${escAS(t.title)}", body:"id=${t.id}\\nsrc=${t.source}\\ntags=${t.tags.join(",")}\\npriority=${t.priority}"}${dueClause}
      return id of newR
    end tell
  `;
  try {
    return osa(script);
  } catch (e) {
    console.error(`pushToReminders failed for "${t.title}":`, (e as Error).message);
    return null;
  }
}

/** Mark a Reminder completed via its id. */
export function markRemindersCompleted(reminderId: string) {
  if (!IS_MAC) return;
  const script = `
    tell application "Reminders"
      set R to first reminder whose id is "${reminderId}"
      set completed of R to true
    end tell
  `;
  try { osa(script); } catch {}
}

/** Pull all reminders (open + completed) from our four target lists. */
export function pullReminders(): Array<{
  id: string;
  list: TaskList;
  name: string;
  body: string;
  due: string | null;
  completed: boolean;
}> {
  if (!IS_MAC) return [];
  const out: Array<any> = [];
  for (const list of ALL_LISTS) {
    const script = `
      tell application "Reminders"
        if not (exists list "${list}") then return ""
        set theList to list "${list}"
        set output to ""
        repeat with R in (every reminder of theList)
          set rid to id of R as string
          set rname to (name of R as string)
          set rbody to ""
          try
            set rbody to (body of R as string)
          end try
          set rdue to ""
          try
            set rdue to (due date of R as string)
          end try
          set rcomp to (completed of R as string)
          set output to output & rid & "|" & rname & "|" & rdue & "|" & rcomp & "|" & (do shell script "echo " & quoted form of rbody & " | base64") & linefeed
        end repeat
        return output
      end tell
    `;
    try {
      const raw = osa(script);
      raw
        .split("\n")
        .filter(Boolean)
        .forEach((line) => {
          const [rid, rname, rdue, rcomp, b64body] = line.split("|");
          let body = "";
          try {
            body = Buffer.from(b64body || "", "base64").toString("utf8");
          } catch {}
          // Convert AppleScript date string → ISO if possible
          let due: string | null = null;
          if (rdue) {
            const d = new Date(rdue);
            if (!isNaN(d.getTime())) due = d.toISOString();
          }
          out.push({
            id: rid,
            list: list as TaskList,
            name: rname,
            body,
            due,
            completed: rcomp === "true",
          });
        });
    } catch (e) {
      console.error(`pullReminders failed for list ${list}:`, (e as Error).message);
    }
  }
  return out;
}

// ─── Supabase bridge ────────────────────────────────────────────────────
type SupabaseRow = Omit<Task, "id"> & {
  id: string; // server-side uuid (matches supabaseId on the local task)
  user_id?: string;
  reminder_external_id: string | null;
  supabase_id: string | null;
  created_at: string;
  updated_at: string;
  completed_at: string | null;
};

async function getSupabase() {
  // Lazy import so plain CLI use without env vars doesn't blow up.
  const url = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
  const key =
    process.env.SUPABASE_SERVICE_ROLE_KEY ||
    process.env.SUPABASE_ANON_KEY ||
    process.env.VITE_SUPABASE_ANON_KEY ||
    process.env.VITE_SUPABASE_PUBLISHABLE_KEY;
  if (!url || !key) {
    return null;
  }
  const { createClient } = await import("@supabase/supabase-js");
  return createClient(url, key, { auth: { persistSession: false } });
}

function rowToTask(row: any): Task {
  return {
    id: row.local_id || row.id,
    title: row.title,
    list: row.list,
    due: row.due,
    priority: row.priority,
    tags: row.tags || [],
    status: row.status,
    source: row.source,
    reminderExternalId: row.reminder_external_id,
    supabaseId: row.id,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
    completedAt: row.completed_at,
  };
}
function taskToRow(t: Task) {
  return {
    local_id: t.id,
    title: t.title,
    list: t.list,
    due: t.due,
    priority: t.priority,
    tags: t.tags,
    status: t.status,
    source: t.source,
    reminder_external_id: t.reminderExternalId,
    completed_at: t.completedAt,
  };
}

export async function pushToSupabase(tasks: Task[]) {
  const sb = await getSupabase();
  if (!sb) {
    console.warn("[sync] no Supabase env (SUPABASE_URL + key) — skipping cloud push");
    return tasks;
  }
  for (const t of tasks) {
    const row = taskToRow(t);
    if (t.supabaseId) {
      const { error } = await sb.from("agent_inbox").update(row).eq("id", t.supabaseId);
      if (error) console.error(`update ${t.id}:`, error.message);
    } else {
      const { data, error } = await sb.from("agent_inbox").insert(row).select("id").single();
      if (error) console.error(`insert ${t.id}:`, error.message);
      else if (data) t.supabaseId = data.id;
    }
  }
  return tasks;
}

export async function pullFromSupabase(): Promise<Task[]> {
  const sb = await getSupabase();
  if (!sb) return [];
  const { data, error } = await sb
    .from("agent_inbox")
    .select("*")
    .order("created_at", { ascending: false })
    .limit(500);
  if (error) {
    console.error("pullFromSupabase:", error.message);
    return [];
  }
  return (data || []).map(rowToTask);
}

// ─── Top-level orchestration ────────────────────────────────────────────
export async function syncAll() {
  const store = loadStore();

  // 1. Pull from Reminders → reconcile into store
  const rems = pullReminders();
  for (const r of rems) {
    const local = store.tasks.find((t) => t.reminderExternalId === r.id);
    if (local) {
      // Update completed status
      if (r.completed && local.status !== "done") {
        local.status = "done";
        local.completedAt = new Date().toISOString();
        local.updatedAt = new Date().toISOString();
      }
      continue;
    }
    // Try fingerprint match
    const fp = fingerprint({ title: r.name, list: r.list, due: r.due });
    const candidate = store.tasks.find(
      (t) => fingerprint(t) === fp && !t.reminderExternalId,
    );
    if (candidate) {
      candidate.reminderExternalId = r.id;
      candidate.updatedAt = new Date().toISOString();
      if (r.completed && candidate.status !== "done") {
        candidate.status = "done";
        candidate.completedAt = new Date().toISOString();
      }
      continue;
    }
    // New task pulled from Reminders
    store.tasks.push({
      id: cryptoUUID(),
      title: r.name,
      list: r.list,
      due: r.due,
      priority: "medium",
      tags: [],
      status: r.completed ? "done" : "open",
      source: "reminders",
      reminderExternalId: r.id,
      supabaseId: null,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      completedAt: r.completed ? new Date().toISOString() : null,
    });
  }

  // 2. Push open local tasks to Reminders (those without external id)
  for (const t of store.tasks) {
    if (t.status === "open" && !t.reminderExternalId) {
      const id = pushToReminders(t);
      if (id) {
        t.reminderExternalId = id;
        t.updatedAt = new Date().toISOString();
      }
    }
    // Mark completed in Reminders
    if (t.status === "done" && t.reminderExternalId) {
      markRemindersCompleted(t.reminderExternalId);
    }
  }

  // 3. Push to Supabase
  await pushToSupabase(store.tasks);

  // 4. Pull from Supabase, merge any rows we don't have
  const cloud = await pullFromSupabase();
  for (const c of cloud) {
    const local = store.tasks.find(
      (t) => t.supabaseId === c.supabaseId || t.id === c.id,
    );
    if (!local) store.tasks.push(c);
  }

  saveStore(store);
  rebuildTodayMd(store.tasks);
  return store.tasks;
}

function cryptoUUID(): string {
  // node 19+ has globalThis.crypto.randomUUID; fall back to a manual gen.
  // @ts-ignore
  if (globalThis.crypto?.randomUUID) return globalThis.crypto.randomUUID();
  return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    const v = c === "x" ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
}
