// cfo-notify — create an approval request + ping Sam via Telegram InlineKeyboard
// Called by CFO scripts; Sam taps APPROVE/DENY from his phone.
// callback_data written as "cb:cfo:approve:TOKEN" in agencyhub_command_queue
// via the existing telegram-webhook SAM_CHAT_ID fork.

// deno-lint-ignore-file no-explicit-any
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SERVICE_KEY  = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const BOT_TOKEN    = Deno.env.get("APEX_TELEGRAM_BOT_TOKEN")!;
const SAM_CHAT_ID  = 6018839640;

const sb = createClient(SUPABASE_URL, SERVICE_KEY, { auth: { persistSession: false } });
const TG = (m: string) => `https://api.telegram.org/bot${BOT_TOKEN}/${m}`;

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

async function sendApprovalMessage(token: string, recipientName: string, recipientEmail: string, amountCents: number, subject: string): Promise<boolean> {
  const dollars = (amountCents / 100).toLocaleString("en-US", { style: "currency", currency: "USD" });
  const msg = [
    `🚨 <b>CFO Recovery Request</b>`,
    ``,
    `<b>To:</b> ${recipientName} (${recipientEmail})`,
    `<b>Subject:</b> ${subject}`,
    `<b>$ at stake:</b> ${dollars}/mo MRR`,
    ``,
    `Tap to decide — this fires the rescue email immediately on APPROVE.`,
  ].join("\n");

  const payload = {
    chat_id: SAM_CHAT_ID,
    text: msg,
    parse_mode: "HTML",
    reply_markup: {
      inline_keyboard: [[
        { text: `✅ APPROVE — Send Rescue`, callback_data: `cfo:approve:${token}` },
        { text: `❌ DENY`,                  callback_data: `cfo:deny:${token}` },
      ]],
    },
  };

  const r = await fetch(TG("sendMessage"), {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(payload),
  });
  if (!r.ok) {
    console.error("tgSend failed", r.status, await r.text());
    return false;
  }
  return true;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });
  if (req.method !== "POST") return new Response("method not allowed", { status: 405, headers: corsHeaders });

  // Auth: require service-role key or internal call
  const auth = req.headers.get("authorization") ?? "";
  if (!auth.startsWith("Bearer ")) return new Response("unauthorized", { status: 401, headers: corsHeaders });

  let body: any;
  try { body = await req.json(); }
  catch { return new Response("bad json", { status: 400, headers: corsHeaders }); }

  const { recipient_email, recipient_name, subject, email_body, amount_cents, draft_gmail_id, context } = body;
  if (!recipient_email || !subject) {
    return new Response(JSON.stringify({ error: "recipient_email and subject required" }), {
      status: 400, headers: { ...corsHeaders, "content-type": "application/json" },
    });
  }

  // Insert approval request — token is auto-generated by the DB default
  const { data: row, error } = await sb.from("cfo_approval_requests").insert({
    type: "email_rescue",
    recipient_email,
    recipient_name: recipient_name ?? null,
    subject,
    body: email_body ?? null,
    amount_cents: amount_cents ?? null,
    draft_gmail_id: draft_gmail_id ?? null,
    context: context ?? {},
  }).select("token, id").single();

  if (error || !row) {
    console.error("insert error", error);
    return new Response(JSON.stringify({ error: "db insert failed", detail: error?.message }), {
      status: 500, headers: { ...corsHeaders, "content-type": "application/json" },
    });
  }

  const sent = await sendApprovalMessage(
    row.token,
    recipient_name ?? recipient_email,
    recipient_email,
    amount_cents ?? 0,
    subject,
  );

  return new Response(JSON.stringify({ ok: true, id: row.id, token: row.token, telegram_sent: sent }), {
    headers: { ...corsHeaders, "content-type": "application/json" },
  });
});
