-- agent_inbox — unified task system mirroring tasks/schema.ts.
-- Source of record for the React UI; bridged to Apple Reminders + tasks.json
-- by tasks/sync.ts. RLS keeps each user pinned to their own rows.

CREATE TABLE IF NOT EXISTS public.agent_inbox (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  local_id text,                                 -- the local UUID generated by the CLI / shortcut
  title text NOT NULL,
  list text NOT NULL CHECK (list IN ('APEX-Daily','Recruiting','Build','Follow-ups')),
  due timestamptz,
  priority text NOT NULL DEFAULT 'medium'
    CHECK (priority IN ('low','medium','high','urgent')),
  tags text[] NOT NULL DEFAULT ARRAY[]::text[],
  status text NOT NULL DEFAULT 'open'
    CHECK (status IN ('open','in_progress','blocked','done','cancelled')),
  source text NOT NULL DEFAULT 'cli'
    CHECK (source IN ('cli','vscode','siri','shortcut','ui','reminders','supabase')),
  reminder_external_id text,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_agent_inbox_user_status
  ON public.agent_inbox (user_id, status);
CREATE INDEX IF NOT EXISTS idx_agent_inbox_user_list
  ON public.agent_inbox (user_id, list);
CREATE INDEX IF NOT EXISTS idx_agent_inbox_user_due
  ON public.agent_inbox (user_id, due);
-- Idempotency for CLI re-pushes that already have a server id locally.
CREATE UNIQUE INDEX IF NOT EXISTS idx_agent_inbox_user_local
  ON public.agent_inbox (user_id, local_id) WHERE local_id IS NOT NULL;
-- Idempotency from Apple Reminders → cloud round-trips.
CREATE UNIQUE INDEX IF NOT EXISTS idx_agent_inbox_user_reminder
  ON public.agent_inbox (user_id, reminder_external_id) WHERE reminder_external_id IS NOT NULL;

-- Touch updated_at automatically.
CREATE OR REPLACE FUNCTION public.agent_inbox_touch_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := now();
  IF NEW.status IN ('done','cancelled') AND OLD.status IS DISTINCT FROM NEW.status THEN
    NEW.completed_at := COALESCE(NEW.completed_at, now());
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_agent_inbox_touch ON public.agent_inbox;
CREATE TRIGGER trg_agent_inbox_touch
  BEFORE UPDATE ON public.agent_inbox
  FOR EACH ROW EXECUTE FUNCTION public.agent_inbox_touch_updated_at();

-- RLS
ALTER TABLE public.agent_inbox ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "agent_inbox_owner_select" ON public.agent_inbox;
CREATE POLICY "agent_inbox_owner_select" ON public.agent_inbox
  FOR SELECT TO authenticated
  USING (user_id = auth.uid());

DROP POLICY IF EXISTS "agent_inbox_owner_insert" ON public.agent_inbox;
CREATE POLICY "agent_inbox_owner_insert" ON public.agent_inbox
  FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "agent_inbox_owner_update" ON public.agent_inbox;
CREATE POLICY "agent_inbox_owner_update" ON public.agent_inbox
  FOR UPDATE TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "agent_inbox_owner_delete" ON public.agent_inbox;
CREATE POLICY "agent_inbox_owner_delete" ON public.agent_inbox
  FOR DELETE TO authenticated
  USING (user_id = auth.uid());

COMMENT ON TABLE public.agent_inbox IS
  'Unified task system. Mirrors tasks/schema.ts. Bridges to Apple Reminders + tasks.json via tasks/sync.ts.';
