-- Head-to-toe audit 2026-08-27: agents comp %/NIPR/EO/override/leader-notes were
-- readable agent-to-agent via the blanket 'leaderboard' SELECT policy (a plain
-- agent saw all 190 rows incl. every comp level + regulatory NPN). Agent-facing
-- surfaces (leaderboards, home counts, portal) select only NON-sensitive columns,
-- so a column-level revoke does not touch them. The 5 admin/manager detail
-- surfaces that need these read them through v_agents_full (staff/own/service
-- scoped), so the base table's sensitive columns are revoked from clients while
-- edge functions keep them via the service role. Writes (UPDATE) are unaffected.
create or replace view public.v_agents_full as
select id, user_id, profile_id, manager_id, agent_code, license_status, license_states, nipr_number, status, start_date, total_policies, total_premium, total_earnings, created_at, updated_at, verified_at, verified_by, invited_by_manager_id, attendance_status, performance_tier, field_training_started_at, has_training_course, has_dialer_login, has_discord_access, potential_rating, evaluation_result, evaluated_at, evaluated_by, is_deactivated, crm_setup_link, weekly_10k_badges, deactivation_reason, switched_to_manager_id, sort_order, portal_password_set, is_inactive, password_required, display_name, has_production_access, production_unlocked_at, max_recruits, ref_slug, onboarding_stage, contract_percentage, override_rate, insuracloud_user_id, is_presenting, stage_changed_at, contracted_at, metadata, onboarding_completed_at, first_appointment_at, first_appointment_set_by, first_deal_at, first_10k_at, telegram_chat_id, telegram_opt_out, next_step_stage_key, next_step_due_at, canonical_agent_id, builder_track, agency_owner_qualified_at, next_action_text, next_action_due_at, leader_notes, al_user_id, training_stage_override, training_stage_override_at, training_stage_override_by, source_application_id, license_expires_at, last_license_alert_at, is_manager, license_number, licensed_at, nipr_verified, nipr_verified_at, notes, comp_percentage, comp_approval_status, comp_approved_at, comp_approved_by, eo_certificate_url, eo_policy_number, eo_expires_at, eo_per_claim_limit, eo_aggregate_limit, eo_deductible, eft_ready, contracting_contact_name, license_progress
from public.agents a
where public.is_agency_staff() or a.user_id = auth.uid() or auth.uid() is null;

grant select on public.v_agents_full to authenticated, service_role;

revoke select on public.agents from authenticated, anon;
grant select (id, user_id, profile_id, manager_id, agent_code, license_status, license_states, status, start_date, total_policies, total_premium, total_earnings, created_at, updated_at, verified_at, verified_by, invited_by_manager_id, attendance_status, performance_tier, field_training_started_at, has_training_course, has_dialer_login, has_discord_access, potential_rating, evaluation_result, evaluated_at, evaluated_by, is_deactivated, crm_setup_link, weekly_10k_badges, deactivation_reason, switched_to_manager_id, sort_order, portal_password_set, is_inactive, password_required, display_name, has_production_access, production_unlocked_at, max_recruits, ref_slug, onboarding_stage, insuracloud_user_id, is_presenting, stage_changed_at, contracted_at, metadata, onboarding_completed_at, first_appointment_at, first_appointment_set_by, first_deal_at, first_10k_at, telegram_opt_out, next_step_stage_key, next_step_due_at, canonical_agent_id, builder_track, agency_owner_qualified_at, next_action_text, next_action_due_at, al_user_id, training_stage_override, training_stage_override_at, training_stage_override_by, source_application_id, license_expires_at, last_license_alert_at, is_manager, licensed_at, nipr_verified, nipr_verified_at, notes, eft_ready, contracting_contact_name, license_progress) on public.agents to authenticated, anon;
